<?php

namespace Wovosoft\LaravelProducts\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductCategories extends Model
{
    use SoftDeletes;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = config('laravel-products.categories.table');
        if (config('laravel-products.categories.fillable') == ['*']) {
            $this->guarded = ['id'];
        } else {
            $this->fillable = config('laravel-products.categories.fillable');
        }
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleting(function ($item) {
            $item->productAssignments()->each(function ($assignment) {
                $assignment->delete();
            });
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
     */
    public function products(): HasManyThrough
    {
        return $this->hasManyThrough(
            config('laravel-products.products.model'),   //output
            config('laravel-products.assignments.products_categories.model'),
            'category_id',    //in assignments table
            'id',          //in categories table
            'id',            //in products table
            'product_id'   //in assignments table
        );
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productAssignments(): HasMany
    {
        return $this->hasMany(config('laravel-products.assignments.products_categories.model'),
            'category_id',
            'id'
        );
    }
}
